### ISSUE TITLE
Waystone Towers Update

### ISSUE THREAD

**Issue by ereese99** [ner07ca/bug-reports#5]
I'm on Fabric and have the normal Waystone mod downloaded, so the new update breaks it for me and I don't wanna switch to Fabric Waystones. Is it possible for you to add a config that allows you to toggle one or the other?

**Comment by ner07ca** [comment]
I don't know how to setup a config like that, but a way to keep all your waystone destinations saved is by having both mods, then replacing all the waystones with Fabric waystones, then you can keep or remove waystone (fabric).


Sorry this is all i could think of for now.

**Comment by ner07ca** [comment]
I will update you when/if I manage to add compatabillity. I plan to release a seperate version which uses the previous waystone mod

**Comment by ner07ca** [comment]
Ok I have added a version with the previous waystones mod. Instructions are on the mod page description on curseforge
