### ISSUE TITLE
[Feature]  Compatibility with "Fabric Waystones"

### ISSUE THREAD

**Issue by MLMII** [ner07ca/bug-reports#6]
Hello, I switched over to Fabric Waystones in order to have more control over how often Waystones spawn in villages and was wondering if were possible to have compatibility with your mod as I like your towers much better than the Zelda parkour ones.

Thank you for your time.

**Comment by ner07ca** [comment]
Well the latest version of the mod supports fabric waystones, there is also instructions on how to get the Waystones (Fabric) mod on the mod page
